name: Draft Release
on:
  schedule:
    - cron: '0 10 * * 1' # Every Monday at 10:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 22
          cache: pnpm
      - run: |
          pnpm install --frozen-lockfile
          bash bin/github-release.sh --verbose draft
        env:
          GH_TOKEN: ${{ github.token }}
