name: Draft Release
on:
  schedule:
    - cron: '0 10 * * 1' # Every Monday at 10:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: |
          npm ci
          bash bin/github-release.sh --verbose draft
        env:
          GH_TOKEN: ${{ github.token }}
