name: Review
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    paths:
      - 'src/assets/**'
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request number to review'
        required: true
        type: number

permissions: {}

jobs:
  review:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: 22
        cache: pnpm
    - name: Verify Review Script
      run: |
        git fetch https://github.com/safe-global/safe-deployments.git main:safe-global-main
        if ! git diff --exit-code safe-global-main -- . ':!src/assets'; then
          echo "ERROR: GitHub review script may not be up-to-date" 1>&2
          exit 1
        fi
    - name: Install Dependencies
      run: |
        pnpm install --frozen-lockfile
    - name: Review PR
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        bash bin/github-review.sh ${{ inputs.pr_number || github.event.number }}
